name: Viru Radio 6H Stream

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install FFmpeg & Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fonts-freefont-ttf
          # System එකේ තියෙන FreeSans ෆොන්ට් එක project එකට copy කරනවා
          cp /usr/share/fonts/truetype/freefont/FreeSansBold.ttf ./font.ttf

      - name: Run Viru Radio Stream
        env:
          YOUTUBE_STREAM_KEY: ${{ secrets.YOUTUBE_STREAM_KEY }}
          TZ: Asia/Colombo
        run: node index.js
