name: Viru Radio 6H Stream

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install FFmpeg & Sinhala Font
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fonts-noto-core
          cp $(find /usr/share/fonts/ -name "NotoSansSinhala-Bold.ttf" -o -name "NotoSansSinhala-Regular.ttf" | head -n 1) ./font.ttf

      - name: Run Viru Radio Stream
        env:
          YOUTUBE_STREAM_KEY: ${{ secrets.YOUTUBE_STREAM_KEY }}
          TZ: Asia/Colombo # ලංකාවේ වෙලාවට Timezone එක හැදුවා
        run: node index.js
